version: '3'

services:
  testnet:
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.geth.dockerfile
    ports:
      - '5000:5000'
    labels:
      kompose.service.expose: testnet
    command: sh /proj/run_geth.sh
  coordinator:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8888:8888'
      - '5354:5354'
    depends_on:
      - 'testnet'
    labels:
      kompose.service.expose: coordinator
    command: >
      bash -c "nc -l -p 5354 &&
      sleep 10 &&
      node /proj/packages/generator/dist/coordinator.js"
  redis:
    image: redis
    ports:
      - '6379:6379'
    labels:
      kompose.service.expose: redis
  organizer:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - 'redis'
      - 'coordinator'
    labels:
      kompose.service.expose: organizer 
    command: bash -c "node /proj/packages/generator/dist/organizer.js"
  wallet:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    depends_on:
      - 'redis'
      - 'organizer'
    labels:
      kompose.controller.type: deployment
    command: > 
      bash -c "sleep 10 && node /proj/packages/generator/dist/wallet.js"
  turner:
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    depends_on:
      - 'wallet'
    command: bash -c "sleep 60 && node /proj/packages/generator/dist/blockturner.js"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/24

