version: '3'

services:
  testnet:
    image: zkopru_testnet_ganache:latest
    build:
      context: ./packages/contracts/
      dockerfile: ../../dockerfiles/Contract.dockerfile
    ports:
      - '5000:5000'
    command: ganache-cli --db=/data -i 20200406 -p 5000 --gasLimit 12000000 --deterministic --host 0.0.0.0 --secure --blockTime 10
  coordinator:
    image: zkopru_node
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8888:8888'
    links:
      - 'testnet'
    depends_on:
      - 'testnet'
    command: bash -c "sleep 5 && node /proj/packages/generator/dist/coordinator.js"
  redis:
    image: redis
    ports:
      - '6379:6379'
  organizer:
    image: zkopru_node
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    links:
      - 'testnet'
      - 'coordinator'
      - 'wallet'
    ports:
      - '8080:8080'
    depends_on:
      - 'wallet'
    command: bash -c "sleep 10 && node /proj/packages/generator/dist/organizer.js"
  wallet:
    image: zkopru_node
    build:
      context: ./
      dockerfile: ./dockerfiles/Generator.dockerfile
    links:
      - 'testnet'
      - 'coordinator'
    depends_on:
      - 'coordinator'
    command: bash -c "sleep 15 && node /proj/packages/generator/dist/wallet.js"
